name: integration-test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NPM
        run: npm init
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
