name: Integration tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.9.7
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          build: npm run build
          start: npm start
