name: Integration tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npm package
        run: npm init -y && npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress/cypress/config.json
