name: Integration tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
      - uses: actions/checkout@v1
      - run: cypress run --config-file cypress/cypress/config.json
